name: Publish Documentation


on:
  push:
    branches:
      - master

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python 3.10
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: requirements/requirements-ubuntu-latest-3.10.txt
      
      - name: Install pinned requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements-ubuntu-latest-3.10.txt --prefer-binary
  
      - name: Install docs requirements
        run: pip install .[docs]

      - name: Build documentation
        run:  mkdocs gh-deploy --force --clean --verbose