name: Testing
on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          # Install a specific version of uv.
          version: "0.5.4"
          enable-cache: true
          cache-dependency-glob: requirements/requirements-ubuntu-latest-${{ matrix.python-version }}.txt
  
      - name: Install dependencies
        run: |
          python -m pip install uv
          uv venv -p ${{ matrix.python-version }}
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
          uv pip install -r requirements/requirements-ubuntu-latest-${{ matrix.python-version }}.txt
          uv pip install polars
          uv pip install -e .

      - name: Run tests
        run: |
          pytest tests/
